### ISSUE TITLE
Add Support For Django 1.8

### ISSUE THREAD

**Issue by Uninen** [vandersonmota/model_mommy#217]
Seems that the just released Django 1.8 breaks mommy code.

Getting following traceback:

Traceback (most recent call last):
  File "/home/uninen/projects/djuninennet/pylib/djuniverse/tests.py", line 130, in setUp
    self.free_request = mommy.make(FreeRequest, status='NEW')
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 74, in make
    return mommy.make(**attrs)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 257, in make
    return self._make(commit=True, **attrs)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 307, in _make
    model_attrs[field.name] = self.generate_value(field)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 416, in generate_value
    generator_attrs = get_required_values(generator, field)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 437, in get_required_values
    key, value = item(field)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 57, in <lambda>
    foreign_key_required = [lambda field: ('model', field.related.parent_model)]
AttributeError: 'ManyToOneRel' object has no attribute 'parent_model'

**Comment by vandersonmota** [comment]
damm Django core devs always breaking my stuff. =P

Thanks for the report!

**Comment by vandersonmota** [comment]
@Uninen Could you provide more details? I just ran the tests under Django 1.8 and couldn't caught any error.

**Comment by vandersonmota** [comment]
Nevermind. Test Runner is broken in django 1.8 as well. bummer =/

**Comment by vandersonmota** [comment]
fixed. =) pip install -U model_mommy

**Comment by dvl** [comment]
Working fine for me, thanks
