### ISSUE TITLE
It's not letting me assign foreign keys

### ISSUE THREAD

**Issue by epicserve** [vandersonmota/model_mommy#241]
I'm having trouble when trying to assign foreign keys. I can't figure out why the following doesn't work.

```python
rp = mommy.make('programs.ReportingPeriod', active=True)
eud = mommy.make('places.ExtensionUnitDirector', reporting_period=rp, director__email='joe@example.com')
```

I get the following traceback:

```
Error
Traceback (most recent call last):
  File "/Users/brento/Sites/xxxx/xxxx/apps/reviews/tests/test_jobs.py", line 11, in test_send_review_email
    eud = mommy.make('places.ExtensionUnitDirector', reporting_period=rp, director__email='joe@example.com')
  File "/Users/brento/.virtualenvs/xxxx/lib/python2.7/site-packages/model_mommy/mommy.py", line 82, in make
    return mommy.make(**attrs)
  File "/Users/brento/.virtualenvs/xxxx/lib/python2.7/site-packages/model_mommy/mommy.py", line 265, in make
    return self._make(commit=True, **attrs)
  File "/Users/brento/.virtualenvs/xxxx/lib/python2.7/site-packages/model_mommy/mommy.py", line 320, in _make
    model_attrs[field.name] = advance_iterator(iterator_attrs[field.name])
TypeError: 'NoneType' object is not callable
```

**Comment by vandersonmota** [comment]
@epicserve I couldn't reproduce this error. Could you provide:
- python version
- django version
- model_mommy version
- database used
- model schema.

Thanks!

**Comment by epicserve** [comment]
@vandersonmota, sorry I normally think to provide those details.

Python 2.7.8
Django 1.8.2
model-mommy 1.2.4
MySQL 5.6.24

```python
class ReportingPeriod(models.Model):

    name = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()
    programming_start_date = models.DateField()
    programming_end_date = models.DateField()
    active = models.BooleanField(default=0)
    directory = models.CharField(max_length=5)
    programming_year = models.CharField(max_length=50)
    objects = managers.ReportingPeriodManager()

    class Meta(object):
        ordering = ('-start_date',)

    def __str__(self):
        return self.name

class CategoryBase(MPTTModel):
    parent = TreeForeignKey('self',
        blank=True,
        null=True,
        related_name='children',
        verbose_name=_('parent'))
    name = models.CharField(max_length=100, verbose_name=_('name'))
    slug = models.SlugField(verbose_name=_('slug'))
    active = models.BooleanField(default=True, verbose_name=_('active'))

class ExtensionUnit(CategoryBase):
    TYPE_CHOICES = (
        ('state', 'State'),
        ('area', 'Service Area'),
        ('district', 'District'),
        ('county', 'County'),
        ('army', 'Army'),
        ('tribe', 'Indian Tribe'),
    )
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)

class ExtensionUnitDirector(models.Model):
    extension_unit = models.ForeignKey(ExtensionUnit)
    director = models.ForeignKey('accounts.User')
    reporting_period = models.ForeignKey('programs.ReportingPeriod')
```

**Comment by vandersonmota** [comment]
Thanks @epicserve 
I'll investigate it further

**Comment by katakumpo** [comment]
@epicserve could you try my patch at https://github.com/vandersonmota/model_mommy/pull/244 ?
It works for my custom ForeignKeys if mommy's make and prepare are working and set up in custum field generators definition.

**Comment by epicserve** [comment]
@katakumpo, your patch worked!

**Comment by katakumpo** [comment]
I added a new pull request with less unrelated changes, that adds (make_gen, prepare_gen) optional definition and should work similary as a sideeffect :)
https://github.com/vandersonmota/model_mommy/pull/251

**Comment by katakumpo** [comment]
I added another more simple pull request for this and my issue: https://github.com/vandersonmota/model_mommy/pull/254/

Still one must explicitly state the custom foreign key in settings, but can just use model_mommy's make as generator (which has prepare attached):

```python
    #in settings.py: 
    MOMMY_CUSTOM_FIELDS_GEN = {'CustomForeignKey': 'model_mommy.mommy.make'}
```

will be enough.
Hope that helps solving the issue.
It would solve mine originally targeted at custom foreign keys (https://github.com/vandersonmota/model_mommy/issues/243).

**Comment by vandersonmota** [comment]
thanks @katakumpo
