### ISSUE TITLE
OneToOneField with "related_name" not recongnized

### ISSUE THREAD

**Issue by aronysidoro** [vandersonmota/model_mommy#272]
Hi,

Is `related_name` an acceptable parameter for `model_mommy`?

I have the following code:

```python
class TreeData(models.Model):
    pass


class TreeLink(models.Model):
    destination = models.OneToOneField(TreeData, related_name='parent_link', null=True)


parent_link = mommy.make(TreeLink)
tree_data = mommy.make(TreeData, parent_link=parent_link)
```

But, when running this, I got the below error:

```python
======================================================================
ERROR: test_create_tree_data (decision_tree.tests.test_factory.FactoryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alelevier/Documents/bsrs/bsrs-django/bigsky/decision_tree/tests/test_factory.py", line 33, in test_create_tree_data
    tree_data = factory.create_tree_data()
  File "/Users/alelevier/Documents/bsrs/bsrs-django/bigsky/decision_tree/tests/factory.py", line 37, in create_tree_data
    tree_data = mommy.make(TreeData, parent_link=parent_link)
  File "/Users/alelevier/.virtualenvs/django19/lib/python3.4/site-packages/model_mommy/mommy.py", line 98, in make
    return mommy.make(**attrs)
  File "/Users/alelevier/.virtualenvs/django19/lib/python3.4/site-packages/model_mommy/mommy.py", line 289, in make
    return self._make(commit=True, **attrs)
  File "/Users/alelevier/.virtualenvs/django19/lib/python3.4/site-packages/model_mommy/mommy.py", line 346, in _make
    return self.instance(model_attrs, _commit=commit)
  File "/Users/alelevier/.virtualenvs/django19/lib/python3.4/site-packages/model_mommy/mommy.py", line 362, in instance
    instance = self.model(**attrs)
  File "/Users/alelevier/.virtualenvs/django19/lib/python3.4/site-packages/django/db/models/base.py", line 443, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'parent_link' is an invalid keyword argument for this function
```

Does `model_mommy` currently support a custom `related_name` on the Django Model, and allow for this?  Am I just calling the `model_mommy` API incorrectly?

If this functionality exists, I wanted to check.  If the functionality isn't currently supported, then I'm thinking to write a pull request for it when I have time.

Thank you

**Comment by vandersonmota** [comment]
Hi @aronysidoro 
This seems to be a bug. Thanks for reporting;

**Comment by vandersonmota** [comment]
@aronysidoro  This, is a standard Django behavior. Even if you try to create using `TreeData.objects.create(parent_link=parent_link)` will raise the same error.

That said because "parent_link" is not really a field to be filled https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey.related_name

In your case, what i think it could be done:
```python
tree_data = mommy.make(TreeData)
parent_link = mommy.make(TreeLink, destination=tree_data)
```
