### ISSUE TITLE
Django 1.9: Support to UUIDField

### ISSUE THREAD

**Issue by berinhard** [vandersonmota/model_mommy#282]
My traceback:

```
Traceback (most recent call last):
  File "/home/bernardo/envs/simulingua/job/tests/test_models.py", line 15, in setUp
    self.job = mommy.make('job.Job')
  File "/home/bernardo/.virtualenvs/simulingua/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 98, in make
    return mommy.make(**attrs)
  File "/home/bernardo/.virtualenvs/simulingua/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 289, in make
    return self._make(commit=True, **attrs)
  File "/home/bernardo/.virtualenvs/simulingua/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 337, in _make
    model_attrs[field.name] = self.generate_value(field, commit)
  File "/home/bernardo/.virtualenvs/simulingua/local/lib/python2.7/site-packages/model_mommy/mommy.py", line 449, in generate_value
    raise TypeError('%s is not supported by mommy.' % field.__class__)
TypeError: <class 'django.db.models.fields.UUIDField'> is not supported by mommy.
```

**Comment by vandersonmota** [comment]
fixed by @berinhard
